name: cacao_leaf_detector
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  camera: ^0.10.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_picker: ^0.8.6
  # image: ^4.0.10
  path: ^1.8.2
  path_provider: ^2.0.11
  shared_preferences: ^2.0.16
  objectbox: ^1.7.1
  objectbox_flutter_libs: ^1.7.1
  
  google_mlkit_commons:
  google_mlkit_object_detection: ^0.6.0
  google_mlkit_image_labeling: ^0.5.0
  # google_mlkit_object_detection:
  #   path: ../google_mlkit_object_detection

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  objectbox_generator: ^1.7.1
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/ml/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/leaf.png"